<?php

/**
 * Implements hook_menu().
 */
function bethel_menu() {
  $items['admin/config/bethel'] = array(
    'title' => 'Bethel',
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('access administration pages'),
    'file path' => drupal_get_path('module', 'system'),
    'file' => 'system.admin.inc',
    'weight' => -99,
  );

  return $items;
}

/**
 * Implements hook_custom_theme().
 */
function bethel_custom_theme() {
  // Ensure the admin theme is used on user login pages.
  if (arg(0) == 'user' && (!arg(1) || arg(1) == 'login' || arg(1) == 'password')) {
    return variable_get('admin_theme', 0);
  }
}

/**
 * Implements hook_html_head_alter().
 */
function bethel_html_head_alter(&$head_elements) {
  $bethel_generator = "Bethel, powered by Drupal (http://bethel.io)";
  
  if (isset($head_elements['system_meta_generator'])) {
    $head_elements['system_meta_generator']['#attributes']['content'] = $bethel_generator;
    $head_elements['system_meta_generator']['#attached']['drupal_add_http_header'][0][1] = $bethel_generator;
  }
  if (isset($head_elements['metatag_generator'])) {
    $head_elements['metatag_generator']['#value'] = $bethel_generator;
    $head_elements['metatag_generator']['#attached']['drupal_add_http_header'][0][1] = $bethel_generator;
  }
}
