<?php

/**
 * Implements hook_block_info().
 */
function campus_switch_block_info() {
  $blocks = array();
  $blocks['campus_switch'] = array(
    'info' => t('Campus switcher'),
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function campus_switch_block_view($delta = '') {
  $domains = domain_domains();
  $output = theme('campus_switch_block', array('domains' => $domains));
  $blocks = array(
    'subject' => t('Select your campus:'),
    'content' => $output,
  );
  return $blocks;
}

/**
 * Implements hook_theme().
 */
function campus_switch_theme() {
  return array(
    'campus_switch_block' => array(
      'variables' => array('domains' => array()),
    ),
  );
}

/**
 * Implements hook_block().
 */
function campus_switch_block($op = 'list', $delta = 0, $edit = array()) {
  $blocks = array();
  switch ($op) {
    case 'list':
      $blocks['campus_switch'] = array(
        'info' => t('Campus switcher'),
        'cache' => BLOCK_CACHE_PER_ROLE,
      );
      break;
    case 'view':
      $domains = domain_domains();
      $output = 'Test';
      $output = theme('campus_switch_block', $domains);
      $blocks = array(
        'subject' => t('Campus switcher'),
        'content' => $output,
      );
      break;
  }
  return $blocks;
}

/**
 * Theme element for the Domain Alias switcher block.
 *
 * @param $domains
 *   The array of active domains defined by domain_domains().
 *
 * @return
 *   HTML output.
 */
function theme_campus_switch_block($variables) {
  $_domain = domain_get_domain();
  $domains = $variables['domains'];
  
  $domain_fields = domain_fieldable_load($_domain['domain_id']);
  
  $output = '';
  $items = array();
  $msg = FALSE;
  $i = 0;
  $active = NULL;
  foreach ($domains as $domain) {
    if ($domain['valid']) {
      $title = $domain['sitename'];
      $allow = TRUE;
    }
    else {
      $title = $domain['sitename'] . ' *';
      $allow = FALSE;
      if (user_access('access inactive domains')) {
        $msg = TRUE;
        $allow = TRUE;
      }
    }
    if ($allow) {
      if ($domain['domain_id'] == $_domain['domain_id']) {
        $title = '<strong>' . $title . '</strong>';
      }
      $items[$i]['data'] = l($title, domain_get_uri($domain), array('absolute' => TRUE, 'html' => TRUE));
      if (!empty($domain['aliases'])) {
        $request = array_reverse(explode('.', $_domain['subdomain']));
        if (isset($_domain['active_alias_id'])) {
          $active = $_domain['active_alias_id'];
        }
        foreach ($domain['aliases'] as $alias_id => $alias) {
          $items[$i]['children'][] = _domain_alias_link($alias, $domain, $request, $active);
        }
      }
      $i++;
    }
  }
  $output .= theme('item_list', array('items' => $items));
  $output .= $domain_fields->field_service_times['und'][0]['safe_value'];
  if ($msg) {
    $output .= t('<em>* Inactive domain.</em>');
  }
  return $output;
}
