<?php

/**
 * Implements hook_block_info().
 */
function campus_switch_block_info() {
  $blocks = array();
  $blocks['campus_switch'] = array(
    'info' => t('Campus switcher'),
  );
  $blocks['first_visit_campus_select'] = array(
    'info' => t('First-visit campus select'),
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function campus_switch_block_view($delta = '') {
  $domains = domain_domains();
  switch ($delta) {
    case 'campus_switch':
      $output = theme('campus_switch_block', array('domains' => $domains));
      $blocks = array(
        'subject' => t('Select your campus:'),
        'content' => array(
          '#markup' => $output,
        ),
      );
      break;
    case 'first_visit_campus_select':
      $output = theme('first_visit_campus_select_block', array('domains' => $domains));
      $blocks = array(
        'subject' => t('Select your campus:'),
        'content' => array(
          '#markup' => $output,
          '#attached' => array('js' => array(
            drupal_get_path('module', 'campus_switch') . '/jquery.cookie.js',
            drupal_get_path('module', 'campus_switch') . '/campus_switch.js',
          )),
        ),
      );
      break;
  }
  return $blocks;
}

/**
 * Implements hook_theme().
 */
function campus_switch_theme() {
  return array(
    'campus_switch_block' => array(
      'variables' => array('domains' => array()),
    ),
    'first_visit_campus_select_block' => array(
      'variables' => array('domains' => array()),
    ),
  );
}

/**
 * Theme element for the Domain Alias switcher block.
 *
 * @param $domains
 *   The array of active domains defined by domain_domains().
 *
 * @return
 *   HTML output.
 */
function theme_campus_switch_block($variables) {
  $_domain = domain_get_domain();
  $domains = $variables['domains'];
  
  $location = _bethel_api_query('location/show/' .domain_conf_variable_get($_domain['domain_id'], 'campus_location'));
  
  $output = '';
  $items = array();
  $msg = FALSE;
  $i = 0;
  $active = NULL;
  foreach ($domains as $domain) {
    if ($domain['valid']) {
      $title = $domain['sitename'];
      $allow = TRUE;
    }
    else {
      $title = $domain['sitename'] . ' *';
      $allow = FALSE;
      if (user_access('access inactive domains')) {
        $msg = TRUE;
        $allow = TRUE;
      }
    }
    if ($allow) {
      if ($domain['domain_id'] == $_domain['domain_id']) {
        $title = '<strong>' . $title . '</strong>';
      }
      $items[$i]['data'] = l($title, domain_get_uri($domain) . '?switch', array('absolute' => TRUE, 'html' => TRUE));
      $i++;
    }
  }
  $output .= theme('item_list', array('items' => $items));
  $output .= '<p>' . preg_replace('/(\d+:\d+\w\w)/i', '<strong>$1</strong>', $location->times) . '</p>';
  return $output;
}

function theme_first_visit_campus_select_block($variables) {
  $_domain = domain_get_domain();
  $domains = $variables['domains'];

  $output = '';
  $items = array();
  $i = 0;
  $active = NULL;
  foreach ($domains as $domain) {
    if ($domain['valid']) {
      $location = _bethel_api_query('location/show/' .domain_conf_variable_get($domain['domain_id'], 'campus_location'));
      $lat_lng = $location->loc[1] . ',' . $location->loc[0];
      $items[$i]['data'] = '<img src="http://maps.googleapis.com/maps/api/staticmap?center=' . $lat_lng . '&zoom=13&size=150x200&maptype=roadmap&markers=color:red%7C' . $lat_lng . '&sensor=false" />';
      $items[$i]['data'] .= '<a>' . $domain['sitename'] . '</a>';
      $items[$i]['data'] .= '<p>' . preg_replace('/(\d+:\d+\w\w)/i', '<strong>$1</strong>', $location->times) . '</p>';
      $items[$i]['location'] = $domain['path'];
      $i++;
    }
  }
  $output .= 'We are one Church with two locations, select your campus below:';
  $output .= theme('item_list', array('items' => $items));
  return $output;
}
