<?php

/**
 * Implements hook_block_info().
 */
function mediaplayer_block_info() {
  $blocks['media-player-referenced'] = array(
    'info' => t('Media Player: Referenced Media'), 
    'cache' => DRUPAL_NO_CACHE,
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function mediaplayer_block_view($delta = '') {
  $block['subject'] = t('Referenced Media');

  if (arg(1)) {
    $count = 0;
    $media = array();

    $result = db_query('SELECT v.field_video_video_url embed FROM {field_revision_field_related_event} e LEFT JOIN {field_revision_field_video} v ON e.entity_id = v.entity_id LEFT JOIN {node} n ON e.entity_id = n.nid WHERE e.bundle = :bundle AND e.field_related_event_target_id = :nid ORDER BY n.created DESC', array(':bundle' => 'media', ':nid' => arg(1)));

    foreach ($result as $record) {      
      if (strpos($record->embed, 'vimeo.com')) {
        $vimeo_id = explode('/', $record->embed);
        $vimeo_id = $vimeo_id[count($vimeo_id)-1];

        array_push($media, array('data' => '<iframe src="//player.vimeo.com/video/' . $vimeo_id . '?badge=0&byline=0&portrait=0&color=00aeef" width="480" height="270" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>', 'class' => array(($count % 2) ? 'even' : 'odd')));

        $count++;
      }
    }

    if (!empty($media)) {
      $block['content'] = theme_item_list(array(
        'items' => $media,
        'title' => "",
        'type' => "ul",
        'attributes' => array()
      ));
    }
  }

  return $block;
}
