<?php

/**
 * Implements hook_block_info().
 */
function service_times_block_block_info() {
  $blocks['service_times'] = array(
    'info' => t('Service Times'),
    'status' => TRUE,
    'cache' => DRUPAL_CACHE_PER_ROLE,
    'region' => 'content',
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages' => '<front>',
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function service_times_block_block_view($delta = '') {
  switch ($delta) {
    case 'service_times':
      $block['subject'] = t("<none>");
      $block['content'] = array(
        '#markup' => theme('service_times_template'),
        '#attached' => array('css' => array(drupal_get_path('module', 'service_times_block') . '/service_times_block.css')),
      );
      break;
  }
  return $block;
}

/**
 * Implements hook_theme().
 */
function service_times_block_theme() {
  return array(
    'service_times_template' => array(
      'template' => 'service_times',
    ),
  );
}
